src/libs/launch.ts
=> Fixed Java classpath seperators for linux

.github/workflows/release.yml, .github/workflows/validation.yml, packages/auth/index.ts
=> Quick trigger automation

packages/forge-installer/forgeweb.ts
=> fix(forgeweb): optimize the grab info strategy (hopefully)

packages/auth/index.module.ts
The payload is sent as "[object Object]" because the method body.toString() does not return the serialized body
There might also be other files where there also is this problem but I have not found any yet.
=> fix: payload is not serialized to JSON

package-lock.json, package.json, packages/common/index.module.ts, packages/common/index.ts, packages/common/system.ts, packages/fabric/index.ts, packages/forge-installer/index.ts, packages/forge/index.ts, packages/installer/index.ts, packages/java-installer/README.md, packages/java-installer/index.ts, packages/java-installer/package.json, packages/java-installer/test.ts, packages/java-installer/tsconfig.json, packages/launch/index.ts, packages/launch/test.ts, packages/liteloader/index.ts, packages/liteloader/package.json, packages/resourcepack/index.ts, packages/task/index.ts, packages/task/test.ts, packages/util/package.json, packages/version/index.ts, scripts/test-env.js
- Extract java installer module from voxelauncher project
- Fix launch on macOS for older minecraft.
- Support macOS game icon & name
- Normalize several parsing API
=> Java Installer Module & Various Fixes

packages/forge/index.ts, packages/task/index.ts, packages/task/test.ts
=> fix: hot fixes

packages/core/launch.ts, packages/core/package.json
- Considered the natives libraries changed before extract natives.
- Fix phantom reference
=> Fix the launch natives check

.github/actions/prepare-pr/index.js, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/validation.yml, CHANGELOG.md, README.md, package.json, packages/client/status.ts, packages/client/test.ts
Fix server status return wrongly.
=> fix(client): fetch server status return wrong value

README.md, packages/installer/forge.ts, packages/installer/liteloader.ts, packages/installer/minecraft.ts, packages/task/index.ts, packages/task/test.ts
- majorly support propagation of progress from child to parent
- support task progressing for more download tasks parent.
=> Make more tasks has progress

packages/core/version.ts, packages/installer/curseforge.ts, packages/installer/diagnose.ts, packages/installer/fabric.ts, packages/installer/forge.ts, packages/installer/index.ts, packages/installer/minecraft.ts, packages/installer/test.ts, packages/installer/tsconfig.json, packages/installer/util.ts, packages/unzip/index.ts, packages/unzip/test.ts, packages/user/auth.test.ts, packages/user/package.json, packages/user/util/index.ts
- fix unzip dir regression
- align concurrency control
- support fabric meta api
- extract installer profile to general installer
- fix task cancel not throw
=> Majorly bug fixes

packages/installer/curseforge.ts, packages/installer/forge.ts, packages/installer/minecraft.ts, packages/installer/util.ts
- Lift the downloader assignment to the top of export function
- Fix curseforge query url concurrency
=> Minor fixes

CONTRIBUTE.md, package-lock.json, package.json, packages/core/version.test.ts, packages/core/version.ts, packages/curseforge/README.md, packages/curseforge/http/base.ts, packages/curseforge/http/index.browser.ts, packages/curseforge/http/index.ts, packages/curseforge/http/package.json, packages/curseforge/http/tsconfig.json, packages/curseforge/index.ts, packages/curseforge/package.json, packages/curseforge/test.ts, packages/curseforge/tsconfig.json, packages/gamesetting/README.md, packages/installer/diagnose.ts, packages/installer/minecraft.ts, packages/resource-manager/README.md, packages/resource-manager/index.ts
- Support curseforge API
- Simplify the post processing of the install profile
=> Curseforge API

packages/nbt/index.ts
=> Prevent losing stacktrace by throwing actual Error

.github/workflows/github-pages.yml, docs/site/index.html, package-lock.json, package.json, tsconfig.json
Add generated documentation from JSDocs in code to GitHub Pages.
=> Add documentation generation with Typedoc

CONTRIBUTE.md, README.md, packages/installer/minecraft.ts, packages/task/index.ts
- Fix wrong pause dispatch in task module
- Unify the support of swapping urls
=> Fixes and update docs

packages/forge-site-parser/index.ts, packages/forge-site-parser/test.ts, packages/installer/http.ts
=> fix(installer): close & handle fd properly

packages/core/launch.ts
=> fix: #221 options.maxMemory overwrite bug

packages/installer/install.e2e.test.ts, packages/installer/profile.ts
=> feat(installer): support forge 1.18

packages/model/block.ts
- Now supports options (x/y rotations, uvlock)
- Correctly supports rotation of 90deg
- Supports rotation scale
- Move "fix" into arguments so it can be zeroed out
=> @xmcl/model - BlockModelFactory.getObject() non-breaking changes

packages/model/block.ts, packages/world/index.ts, packages/world/test.ts
PR for both issues noticed with my recent PR. This passes all tests on my machine for the relevant sections.
Also reenabled the disabled `/world` tests
=> @xmcl/world - Pre116 test fixes, @xmcl/model - UV rotational fixes

packages/curseforge/package.json
=> fix: build modrinth types

packages/installer/README.md, packages/task/README.md
=> fix: wrong usage in readme
